### ISSUE TITLE
NullPointerException on PubnativeConfigManager.java

### ISSUE THREAD

**Issue by andreaboi83** [pubnative/pubnative-android-mediation-sdk#2] opened 2017-02-09 09:45 UTC
Hi, I found on Crashlitics that sometimes the PubnativeConfigManager crash on an equals on a null String object. 

The crash appens on line 268 (for the version I currently use, the 1.2.4), inside the method `configNeedsUpdate(PubnativeConfigManager.java:268)`, but the code is the same as in the last version of the mediation sdk.

**Comment by cerberillo** [comment] 2017-02-09 10:53
Hey @andreaboi83 thank you for reporting this problem:

Can you please paste also the crashlytics stacktrace or something to dive deeper here? It looks like the problem is with a null `request` item or a null `storedAppToken` one. But just to be on the safe side I'll like to check the details

**Comment by andreaboi83** [comment] 2017-02-09 11:16
@cerberillo you're welcome!

The stacktrace suggests that the problem is with a null `storedAppToken`:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at net.pubnative.mediation.config.PubnativeConfigManager.configNeedsUpdate(PubnativeConfigManager.java:268)
       at net.pubnative.mediation.config.PubnativeConfigManager.getNextConfig(PubnativeConfigManager.java:151)
       at net.pubnative.mediation.config.PubnativeConfigManager.doNextConfigRequest(PubnativeConfigManager.java:144)
       at net.pubnative.mediation.config.PubnativeConfigManager.getConfig(PubnativeConfigManager.java:117)
       at net.pubnative.mediation.config.PubnativePlacement.load(PubnativePlacement.java:102)
       at net.pubnative.mediation.request.PubnativeNetworkWaterfall.initialize(PubnativeNetworkWaterfall.java:100)
       at net.pubnative.mediation.request.PubnativeNetworkRequest.start(PubnativeNetworkRequest.java:108)
...`

**Comment by cerberillo** [comment] 2017-02-09 14:10
so yeah, as stated by the error, storedAppToken is null at this point. I'll add a check before to ensure to download the config if this case is given.

Upcoming version `1.2.9` will be released soon @andreaboi83  👍

**Comment by andreaboi83** [comment] 2017-02-09 14:11
Ok, thanks!

**Comment by cerberillo** [comment] 2017-02-09 15:02
@andreaboi83 version issued, and available on bintray, thanks

**Closed by cerberillo** 2017-02-09 15:02 UTC
